const STORAGE_KEYS = {
  PEOPLE: "PEOPLE",
  GIFTS: "GIFTS",
  APP_SETTINGS: "APP_SETTINGS",
};

const STATIC = {
  APPROACHING_BIRTHDAYS: "APPROACHING_BIRTHDAYS",
  PAST_BIRTHDAYS: "PAST_BIRTHDAYS",
};

const FALLBACK = {};

export { STORAGE_KEYS, FALLBACK, STATIC };
